// flow-typed signature: b1b78530266aa769abbf3c8061341ae3
// flow-typed version: <<STUB>>/feature-toggle_v0.3.x/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feature-toggle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feature-toggle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feature-toggle/dist/feature-toggle-client' {
  declare module.exports: any;
}

declare module 'feature-toggle/feature-toggle-client' {
  declare module.exports: any;
}

declare module 'feature-toggle/gruntfile' {
  declare module.exports: any;
}

declare module 'feature-toggle/test/resources/jquery' {
  declare module.exports: any;
}

declare module 'feature-toggle/test/resources/qunit' {
  declare module.exports: any;
}

declare module 'feature-toggle/test/test-client' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feature-toggle/dist/feature-toggle-client.js' {
  declare module.exports: $Exports<'feature-toggle/dist/feature-toggle-client'>;
}
declare module 'feature-toggle/feature-toggle-client.js' {
  declare module.exports: $Exports<'feature-toggle/feature-toggle-client'>;
}
declare module 'feature-toggle/gruntfile.js' {
  declare module.exports: $Exports<'feature-toggle/gruntfile'>;
}
declare module 'feature-toggle/test/resources/jquery.js' {
  declare module.exports: $Exports<'feature-toggle/test/resources/jquery'>;
}
declare module 'feature-toggle/test/resources/qunit.js' {
  declare module.exports: $Exports<'feature-toggle/test/resources/qunit'>;
}
declare module 'feature-toggle/test/test-client.js' {
  declare module.exports: $Exports<'feature-toggle/test/test-client'>;
}
