service: cyf

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  prod: prod

  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameters
      Resource: '*'

functions:
  donate:
    handler: handler.stripe
    environment: ${file(env.donate.yml):${opt:stage}}
    description: Handles Stripe requests.
    events:
      - http:
          path: donate
          method: POST
          integration: lambda
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  pipedrive:
    handler: handler.pipedrive
    environment: ${file(env.pipedrive.yml):${opt:stage}}
    description: Handles reading and writting the PipeDrive account.
    events:
          - http:
              path: database
              method: POST
              integration: lambda
              cors:
                origin: '*'
                headers:
                  - Content-Type
                  - X-Amz-Date
                  - Authorization
                  - X-Api-Key
                  - X-Amz-Security-Token
                  - X-Amz-User-Agent
                  - Access-Control-Allow-Origin